In [44]:
import numpy as np
import math as m

In [45]:
i_mat = np.array([
                    1,0,0,0,
                    0,1,0,0,
                    0,0,1,0,
                    0,0,0,1
]).reshape(4,4)

In [46]:
def point_trans(mat,p_vector):
    return mat@p_vector

In [101]:
def generic_rot(m_vector,theta):

    # unitize axis
    m_vec = np.array(m_vector).reshape(3,1)

    if round(np.linalg.norm(m_vec),2) != 1:
        raise TypeError('UNITIZE VECTOR')

    if theta > 4*m.pi:
        theta = theta*(m.pi/180)
    else: 
        theta = theta

    m_unit = m_vec
    v = 1 - m.cos(theta)

    gen_trans = np.zeros([4,4])
    gen_trans[0][0] = (m_unit[0]**2)*v + m.cos(theta)
    gen_trans[0][1] = m_unit[0]*m_unit[1]*v - m_unit[2]*m.sin(theta)
    gen_trans[0][2] = m_unit[0]*m_unit[2]*v + m_unit[1]*m.sin(theta)
    gen_trans[1][0] = m_unit[0]*m_unit[1]*v + m_unit[2]*m.sin(theta)
    gen_trans[1][1] = (m_unit[1]**2)*v + m.cos(theta)
    gen_trans[1][2] = m_unit[1]*m_unit[2]*v - m_unit[0]*m.sin(theta)
    gen_trans[2][0] = m_unit[0]*m_unit[2]*v - m_unit[1]*m.sin(theta)
    gen_trans[2][1] = m_unit[1]*m_unit[2]*v + m_unit[0]*m.sin(theta)
    gen_trans[2][2] = (m_unit[2]**2)*v + m.cos(theta)
    gen_trans[3][3] = 1

    return gen_trans

In [48]:
def x_rot(mat,theta):
    
    if theta > 4*m.pi:
        theta = theta*(m.pi/180)
    else: 
        theta = theta

    x_mat = np.array([
                        1,0,0,0,
                        0,m.cos(theta),-m.sin(theta),0,
                        0,m.sin(theta),m.cos(theta),0,
                        0,0,0,1
    ]).reshape(4,4)
    
    return mat@x_mat

In [49]:
def y_rot(mat,theta):

    if theta > 4*m.pi:
        theta = theta*(m.pi/180)
    else: 
        theta = theta

    y_mat = np.array([
                        m.cos(theta),0,m.sin(theta),0,
                        0,1,0,0,
                        -m.sin(theta),0,m.cos(theta),0,
                        0,0,0,1
    ]).reshape(4,4)
    
    return mat@y_mat

In [50]:
def z_rot(mat,theta):

    if theta > 4*m.pi:
        theta = theta*(m.pi/180)
    else: 
        theta = theta

    z_mat = np.array([
                        m.cos(theta),-m.sin(theta),0,0,
                        m.sin(theta),m.cos(theta),0,0,
                        0,0,1,0,
                        0,0,0,1
    ]).reshape(4,4)

    return mat@z_mat

In [51]:
m_vector = [2,4,7]
theta = 60

AC_T = np.array([
                    1,0,0,3,
                    0,1,0,4,
                    0,0,1,-2,
                    0,0,0,1
                ]).reshape(4,4)

DB_T = np.array([
                    1,0,0,-3,
                    0,1,0,-4,
                    0,0,1,2,
                    0,0,0,1
                ]).reshape(4,4)


AC_T@generic_rot(m_vector,theta)@DB_T


array([[ 0.52898551, -0.67182943,  0.5184781 ,  5.13731742],
       [ 0.78777146,  0.61594203, -0.00561586, -0.83831423],
       [-0.31557955,  0.41141296,  0.85507246, -0.98876827],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [123]:
p1 = np.array([
                1,0,0,2,
                0,1,0,4,
                0,0,1,-5,
                0,0,0,1
]).reshape(4,4)

AC_T = x_rot(p1,35)

print(x_rot(p1,35),'\n')

print(np.linalg.inv(AC_T),'\n')

a_m = [2,3,4] / np.linalg.norm([2,3,4])

a_p2 = np.array([
                1,0,0,5,
                0,1,0,3,
                0,0,1,5,
                0,0,0,1
]).reshape(4,4)

d_m = np.linalg.inv(AC_T[:3,:3])@a_m

print('dm\n',d_m,'\n')

d_p2 = (np.linalg.inv(AC_T)@a_p2)[:,-1].T
rotd_p2 = np.array([
                    1,0,0,d_p2[0],
                    0,1,0,d_p2[1],
                    0,0,1,d_p2[2],
                    0,0,0,1
]).reshape(4,4)
print('d_p2\n',rotd_p2)
Md_p2 = np.array([
                    1,0,0,-d_p2[0],
                    0,1,0,-d_p2[1],
                    0,0,1,-d_p2[2],
                    0,0,0,1
]).reshape(4,4)

print('dp2\n',d_p2,'\n')

m_rot = generic_rot(d_m,75)

rot = rotd_p2@m_rot

CB_T = rot@Md_p2

AC_T@CB_T

[[ 1.          0.          0.          2.        ]
 [ 0.          0.81915204 -0.57357644  4.        ]
 [ 0.          0.57357644  0.81915204 -5.        ]
 [ 0.          0.          0.          1.        ]] 

[[ 1.          0.          0.         -2.        ]
 [ 0.          0.81915204  0.57357644 -0.408726  ]
 [ 0.         -0.57357644  0.81915204  6.39006597]
 [ 0.          0.          0.          1.        ]] 

dm
 [0.37139068 0.88238003 0.28891945] 

d_p2
 [[1.         0.         0.         3.        ]
 [0.         1.         0.         4.91661232]
 [0.         0.         1.         8.76509688]
 [0.         0.         0.         1.        ]]
dp2
 [3.         4.91661232 8.76509688 1.        ] 



array([[ 0.3610509 , -0.03618404,  0.93184385, -4.07295142],
       [ 0.87081948,  0.3705858 , -0.32301642,  1.39678508],
       [-0.33364006,  0.92809314,  0.16531011, -0.0111131 ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])