In [4]:
import numpy as np
import pandas as pd
import math as m

In [58]:
def fwd_analysis(A_vec,alpha_vec,S_vec,theta_rad):
    # A_vec is a 1xN vector that contains link length (a12 through a56)
    # alpha_vec is a 1xN vector that contains twist angles (alpha12 through alpha56)
    # S_vec is a 1xN vector that contains joint offset (S2 through S5)
    # theta_rad contains the given joint angles in radians where theta_rad[0] is phi_1

    i=0
    T_F1 = np.array([m.cos(theta_rad[i]),-m.sin(theta_rad[i]),0,0,
                     m.sin(theta_rad[i]),m.cos(theta_rad[i]),0,0,
                     0,0,1,0,
                     0,0,0,1
        
    ]).reshape(4,4)

    i+=1
    j=0
    T_12 = np.array([m.cos(theta_rad[i]),-m.sin(theta_rad[i]),0,A_vec[j],
                        m.sin(theta_rad[i])*m.cos(alpha_vec[j]),m.cos(theta_rad[i])*m.cos(alpha_vec[j]),-m.sin(alpha_vec[j]),-m.sin(alpha_vec[j])*S_vec[j],
                        m.sin(theta_rad[i])*m.sin(alpha_vec[j]),m.cos(theta_rad[i])*m.sin(alpha_vec[j]),m.cos(alpha_vec[j]),m.cos(alpha_vec[j])*S_vec[j],
                        0,0,0,1
            
        ]).reshape(4,4)

    i+=1
    j+=1
    T_23 = np.array([m.cos(theta_rad[i]),-m.sin(theta_rad[i]),0,A_vec[j],
                        m.sin(theta_rad[i])*m.cos(alpha_vec[j]),m.cos(theta_rad[i])*m.cos(alpha_vec[j]),-m.sin(alpha_vec[j]),-m.sin(alpha_vec[j])*S_vec[j],
                        m.sin(theta_rad[i])*m.sin(alpha_vec[j]),m.cos(theta_rad[i])*m.sin(alpha_vec[j]),m.cos(alpha_vec[j]),m.cos(alpha_vec[j])*S_vec[j],
                        0,0,0,1
        
    ]).reshape(4,4)

    i+=1
    j+=1
    T_34 = np.array([m.cos(theta_rad[i]),-m.sin(theta_rad[i]),0,A_vec[j],
                        m.sin(theta_rad[i])*m.cos(alpha_vec[j]),m.cos(theta_rad[i])*m.cos(alpha_vec[j]),-m.sin(alpha_vec[j]),-m.sin(alpha_vec[j])*S_vec[j],
                        m.sin(theta_rad[i])*m.sin(alpha_vec[j]),m.cos(theta_rad[i])*m.sin(alpha_vec[j]),m.cos(alpha_vec[j]),m.cos(alpha_vec[j])*S_vec[j],
                        0,0,0,1
        
    ]).reshape(4,4)

    i+=1
    j+=1
    T_45 = np.array([m.cos(theta_rad[i]),-m.sin(theta_rad[i]),0,A_vec[j],
                        m.sin(theta_rad[i])*m.cos(alpha_vec[j]),m.cos(theta_rad[i])*m.cos(alpha_vec[j]),-m.sin(alpha_vec[j]),-m.sin(alpha_vec[j])*S_vec[j],
                        m.sin(theta_rad[i])*m.sin(alpha_vec[j]),m.cos(theta_rad[i])*m.sin(alpha_vec[j]),m.cos(alpha_vec[j]),m.cos(alpha_vec[j])*S_vec[j],
                        0,0,0,1
        
    ]).reshape(4,4)

    i+=1
    j+=1
    T_56 = np.array([m.cos(theta_rad[i]),-m.sin(theta_rad[i]),0,A_vec[j],
                        m.sin(theta_rad[i])*m.cos(alpha_vec[j]),m.cos(theta_rad[i])*m.cos(alpha_vec[j]),-m.sin(alpha_vec[j]),-m.sin(alpha_vec[j])*S_vec[j],
                        m.sin(theta_rad[i])*m.sin(alpha_vec[j]),m.cos(theta_rad[i])*m.sin(alpha_vec[j]),m.cos(alpha_vec[j]),m.cos(alpha_vec[j])*S_vec[j],
                        0,0,0,1
        
    ]).reshape(4,4)

    T_F6 = T_F1@T_12@T_23@T_34@T_45@T_56

    return T_F6

In [84]:
## BOOK FUNCTION TEST COMPARISON
BOOK_VAL = np.array([0.997,-0.002,0.079,18.577,
                     0.064,0.614,-0.787,23.457,
                     -0.047,0.789,0.612,11.750,
                     0,0,0,1

]).reshape(4,4)

##
A_vec = np.array([0,17,0.8,0,0

])

alpha_vec = np.array([90,0,270,90,90
    
])*(m.pi/180) # convert to radians

S_vec = np.array([5.9,0,17,0,4
    
])

theta_rad = np.array([5*m.pi/4,5*m.pi/6,-m.pi/3,m.pi/4,m.pi/3,-m.pi/6
    
])

T_F6 = fwd_analysis(A_vec,alpha_vec,S_vec,theta_rad).round(2)
print(T_F6 == BOOK_VAL.round(2))
print(f'\n\n{BOOK_VAL.round(2)}\n\n{T_F6}')
print('\n\nfwd analysis correct, textbook has inconsistent rounding')

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


[[ 1.   -0.    0.08 18.58]
 [ 0.06  0.61 -0.79 23.46]
 [-0.05  0.79  0.61 11.75]
 [ 0.    0.    0.    1.  ]]

[[ 1.   -0.    0.08 18.58]
 [ 0.06  0.61 -0.79 23.46]
 [-0.05  0.79  0.61 11.75]
 [ 0.    0.    0.    1.  ]]


fwd analysis correct, textbook has inconsistent rounding


In [90]:
## UFID is 57758617 -> forward analysis for Cincinnati Milacron T3-776

# link length in INCHES
A_vec = np.array([0,44,0,0,0

])

# twist angle in DEGREES
alpha_vec = np.array([90,0,270,90,90
    
])*(m.pi/180) ## convert to radians ##


# joint offest in INCHES
S_6 = 6
S_vec = np.array([0,0,55,0,S_6
    
]) # PICK S_6

# joint angle in RADIANS... ## VARIABLE (SET VALUES)
phi_1 = m.pi
th_2 = m.pi
th_3 = m.pi
th_4 = m.pi
th_5 = m.pi
th_6 = m.pi

theta_rad = np.array([phi_1,th_2,th_3,th_4,th_5,th_6
    
])

Milacron_t3 = fwd_analysis(A_vec,alpha_vec,S_vec,theta_rad)
print(Milacron_t3.round(3))

[[ 1.  0. -0. 44.]
 [-0.  1. -0. -0.]
 [ 0.  0.  1. 61.]
 [ 0.  0.  0.  1.]]
