In [2]:
import numpy as np
import math as m

In [7]:
## Problem 2.3 Part A
BA_T = np.array(
                [
                    m.sqrt(3)/2,0,0.5,20,
                    0,-1,0,0,
                    0.5,0,-m.sqrt(3)/2,0,
                    0,0,0,1
                 ]
            ).reshape(4,4)

CA_T = np.array(
                [
                    m.sqrt(2)/2,m.sqrt(2)/2,0,0,
                    m.sqrt(2)/2,-m.sqrt(2)/2,0,0,
                    0,0,-1,10,
                    0,0,0,1
                 ]
            ).reshape(4,4)

DB_T = np.array(
                [
                    1,0,0,0,
                    0,m.sqrt(3)/2,0.5,10,
                    0,-0.5,m.sqrt(3)/2,0,
                    0,0,0,1
                 ]
            ).reshape(4,4)

CB_T = np.matmul(
                    CA_T,
                    np.linalg.inv(BA_T)
                )

CD_T = np.matmul(
                    CB_T,
                    np.linalg.inv(DB_T)
                )

print(f"Transforming from D to C \n {CD_T}")

Transforming from D to C 
 [[  0.61237244  -0.43559574   0.65973961  -7.89149131]
 [  0.61237244   0.78914913  -0.04736717 -20.13894002]
 [ -0.5          0.4330127    0.75        15.66987298]
 [  0.           0.           0.           1.        ]]


In [20]:
## Problem 2.3 Part B

# put in homogeneous coords
D_p1 = np.array(
    [
        20,-30,5,1
    ]
            ).reshape(4,1)

# in Frame A
AD_T = np.matmul(
                    np.linalg.inv(BA_T),
                    np.linalg.inv(DB_T)
                )

A_p1 = np.matmul(
                    AD_T,
                    D_p1
                )
# in Frame B
B_p1 = np.matmul(
                    np.linalg.inv(DB_T),
                    D_p1
                )

# in Frame C
C_p1 = np.matmul(
                    CD_T,
                    D_p1
                )

print(f"P1 in A:\n{A_p1}\n\nP1 in B:\n{B_p1}\n\nP1 in C:\n{C_p1}")

P1 in A:
[[-7.83493649]
 [37.14101615]
 [13.57050808]
 [ 1.        ]]

P1 in B:
[[ 20.        ]
 [-37.14101615]
 [-15.66987298]
 [  1.        ]]

P1 in C:
[[ 20.72252766]
 [-31.8028011 ]
 [ -3.57050808]
 [  1.        ]]


In [93]:
## Problem 2.4

AC_T = np.array([
                    1,0,0,3,
                    0,1,0,4,
                    0,0,1,-2,
                    0,0,0,1
                ]).reshape(4,4)

# unitize axis
m_vec = np.array([
    2,4,7
            ]).reshape(3,1)
theta_ang = 60
theta_rad = 60*(m.pi/180)

m_unit = m_vec / np.linalg.norm(m_vec)
v = 1 - m.cos(theta_rad)

CD_T = np.zeros([4,4])
CD_T[0][0] = (m_unit[0]**2)*v + m.cos(theta_rad)
CD_T[0][1] = m_unit[0]*m_unit[1]*v - m_unit[2]*m.sin(theta_rad)
CD_T[0][2] = m_unit[0]*m_unit[2]*v + m_unit[1]*m.sin(theta_rad)
CD_T[1][0] = m_unit[0]*m_unit[1]*v + m_unit[2]*m.sin(theta_rad)
CD_T[1][1] = (m_unit[1]**2)*v + m.cos(theta_rad)
CD_T[1][2] = m_unit[1]*m_unit[2]*v - m_unit[0]*m.sin(theta_rad)
CD_T[2][0] = m_unit[0]*m_unit[2]*v - m_unit[1]*m.sin(theta_rad)
CD_T[2][1] = m_unit[1]*m_unit[2]*v + m_unit[0]*m.sin(theta_rad)
CD_T[2][2] = (m_unit[2]**2)*v + m.cos(theta_rad)
CD_T[3][3] = 1

DB_T = np.array([
                    1,0,0,-3,
                    0,1,0,-4,
                    0,0,1,2,
                    0,0,0,1
                ]).reshape(4,4)

AD_T = np.matmul(
                    AC_T,
                    CD_T
                )

AB_T = np.matmul(
                    AD_T,
                    DB_T
                )

print(f"Transform from A to C:\n{AC_T}\n\nTransform from C to D:\n{CD_T}\n\nTransform from D to B:\n{DB_T}\n\nTransform from A to D:\n{AD_T}\n\nTransform from A to B:\n{AB_T}")

Transform from A to C:
[[ 1  0  0  3]
 [ 0  1  0  4]
 [ 0  0  1 -2]
 [ 0  0  0  1]]

Transform from C to D:
[[ 0.52898551 -0.67182943  0.5184781   0.        ]
 [ 0.78777146  0.61594203 -0.00561586  0.        ]
 [-0.31557955  0.41141296  0.85507246  0.        ]
 [ 0.          0.          0.          1.        ]]

Transform from D to B:
[[ 1  0  0 -3]
 [ 0  1  0 -4]
 [ 0  0  1  2]
 [ 0  0  0  1]]

Transform from A to D:
[[ 0.52898551 -0.67182943  0.5184781   3.        ]
 [ 0.78777146  0.61594203 -0.00561586  4.        ]
 [-0.31557955  0.41141296  0.85507246 -2.        ]
 [ 0.          0.          0.          1.        ]]

Transform from A to B:
[[ 0.52898551 -0.67182943  0.5184781   5.13731742]
 [ 0.78777146  0.61594203 -0.00561586 -0.83831423]
 [-0.31557955  0.41141296  0.85507246 -0.98876827]
 [ 0.          0.          0.          1.        ]]


In [6]:
## Problem 2.8
theta_ang = 30
theta_rad = 30*(m.pi/180)

AD_T = np.array([
                    1,0,0,10,
                    0,1,0,20,
                    0,0,1,10,
                    0,0,0,1

                ]).reshape(4,4)

DE_T = np.array([
                    1,0,0,0,
                    0,m.cos(theta_rad),-m.sin(theta_rad),0,
                    0,m.sin(theta_rad),m.cos(theta_rad),0,
                    0,0,0,1
                ]).reshape(4,4)

EB_T = np.array([
                    1,0,0,-10,
                    0,1,0,-20,
                    0,0,1,-10,
                    0,0,0,1
                ]).reshape(4,4)

AE_T = np.matmul(
                    AD_T,
                    DE_T
                )

AB_T = np.matmul(
                    AE_T,
                    EB_T
                )

# unitize axis
m_vec = np.array([
    2,4,6
            ]).reshape(3,1)
theta_ang = 60
theta_rad = 60*(m.pi/180)

m_unit = m_vec / np.linalg.norm(m_vec)
v = 1 - m.cos(theta_rad)

AC_T = np.zeros([4,4])
AC_T[0][0] = (m_unit[0]**2)*v + m.cos(theta_rad)
AC_T[0][1] = m_unit[0]*m_unit[1]*v - m_unit[2]*m.sin(theta_rad)
AC_T[0][2] = m_unit[0]*m_unit[2]*v + m_unit[1]*m.sin(theta_rad)
AC_T[1][0] = m_unit[0]*m_unit[1]*v + m_unit[2]*m.sin(theta_rad)
AC_T[1][1] = (m_unit[1]**2)*v + m.cos(theta_rad)
AC_T[1][2] = m_unit[1]*m_unit[2]*v - m_unit[0]*m.sin(theta_rad)
AC_T[2][0] = m_unit[0]*m_unit[2]*v - m_unit[1]*m.sin(theta_rad)
AC_T[2][1] = m_unit[1]*m_unit[2]*v + m_unit[0]*m.sin(theta_rad)
AC_T[2][2] = (m_unit[2]**2)*v + m.cos(theta_rad)
AC_T[3][3] = 1

BC_T = np.matmul(
                    np.linalg.inv(AB_T),
                    AC_T
                )

#print(f"A to D:\n{AD_T}\n\nD to E:\n{DE_T}\n\nE to B:{EB_T}\n\nA to E:\n{AE_T}\n\nA to B:\n{AB_T}")
print(f"A to C:\n{AC_T}\n\n")
print(f"B to C:\n{BC_T}")

A to C:
[[ 0.53571429 -0.6229365   0.57005291  0.        ]
 [ 0.76579365  0.64285714 -0.01716931  0.        ]
 [-0.35576719  0.44574074  0.82142857  0.        ]
 [ 0.          0.          0.          1.        ]]


B to C:
[[ 0.53571429 -0.6229365   0.57005291  0.        ]
 [ 0.48531316  0.77960099  0.39584523 -2.32050808]
 [-0.69100025  0.06459423  0.71996267 11.33974596]
 [ 0.          0.          0.          1.        ]]
