In [2]:
import numpy as np
import math as m

In [33]:
BA_T = np.array(
                [
                    m.sqrt(3)/2,0,0.5,20,
                    0,-1,0,0,
                    0.5,0,-m.sqrt(3)/2,0,
                    0,0,0,1
                 ]
            ).reshape(4,4)

CA_T = np.array(
                [
                    m.sqrt(2)/2,m.sqrt(2)/2,0,0,
                    m.sqrt(2)/2,-m.sqrt(2)/2,0,0,
                    0,0,-1,10,
                    0,0,0,1
                 ]
            ).reshape(4,4)

DB_T = np.array(
                [
                    1,0,0,0,
                    0,m.sqrt(3)/2,0.5,10,
                    0,-0.5,m.sqrt(3)/2,0,
                    0,0,0,1
                 ]
            ).reshape(4,4)

CB_T = np.matmul(
                    CA_T,
                    np.linalg.inv(BA_T)
                )

CD_T = np.matmul(
                    CB_T,
                    np.linalg.inv(DB_T)
                )

print(f"Transforming from D to C \n {CD_T}")

Transforming from D to C 
 [[  0.61237244  -0.43559574   0.65973961  -7.89149131]
 [  0.61237244   0.78914913  -0.04736717 -20.13894002]
 [ -0.5          0.4330127    0.75        15.66987298]
 [  0.           0.           0.           1.        ]]


In [ ]:
p1 = np.array(
    [

    ]
            )